etc/nginx/conf.d/local.conf, public/config/local.js, src/App.tsx, src/AppConfig.d.ts, src/DicomWebManager.tsx, src/components/CaseViewer.tsx, src/components/Header.tsx, src/components/SlideViewer.tsx
This PR adds two configuration parameters to address #42:
* `disableWorklist` to disable the worklist. If `true` users can then no longer route to the worklist to select a study, but have to route to a specific study directly.
* `disableAnnotationTools` to disable the annotation tools of the slide viewer. If `true` users can no longer draw new annotation or edit existing annotations. However, existing annotations will still be displayed.
=> Configure application to disable workflist and annotation tools

package.json, yarn.lock
Update the version of the dicom-microscopy-viewer. The [0.32.2 release](https://github.com/MGHComputationalPathology/dicom-microscopy-viewer/releases/tag/v0.32.2) changed the behavior of the viewer to avoid inclusion of the `viewport` query parameter into the URL of retrieve rendered requests unless it's really needed.
=> Retrieve OVERVIEW image by default without using "viewport" query parameter

src/components/Worklist.tsx
When routing to the worklist, first determine all total number of available studies.
=> Fix pagination of worklist

package.json
https://github.com/MGHComputationalPathology/dicom-microscopy-viewer/releases/tag/v0.33.0 that update OpenLayers tp 6.7.0
=> Update dep dicom-microscopy-viewer

.github/workflows/deploy_firebase_hosting.yml, .github/workflows/deploy_gh_pages.yml, .github/workflows/run_container_tests.yml, .github/workflows/run_unit_tests.yml, Dockerfile, etc/nginx/conf.d/local.conf, public/config/local.js
- Install node version 14+, which is required for building Slim but is not provided by current Debian distributions
- Expose viewer at root location for simplicity
- Add workflow to test container deployment
=> Fix container deployment on localhost

src/components/CaseViewer.tsx, src/components/ClinicalTrial.tsx, src/components/SlideViewer.tsx, types/dicom-microscopy-viewer/index.d.ts
So far, the case viewer just displays the information about the patient and the study. This PR introduces changes to also display the information about the clinical trial (if available). Specifically, it adds a panel in the case viewer that displays type 1 and 2 attributes of the Clinical Trial Subject and Clinical Trial Study modules.
=> Add case viewer panel for clinical trial metadata

src/components/SlideViewer.tsx, src/data/slides.tsx
Currently slides are sorted by Series Number. The value of this attribute may not be very reliable. Therefore, we instead sort slides by Container Identifier instead. This is a type 1 attribute and required to be present.
=> Sort slides by container identifier

src/data/slides.tsx, types/dicom-microscopy-viewer/index.d.ts
=> Support images with different FrameOfReferenceUIDs

package.json, src/App.tsx, src/AppConfig.d.ts, src/components/AnnotationGroupItem.tsx, src/components/AnnotationGroupList.tsx, src/components/CaseViewer.tsx, src/components/SlideItem.tsx, src/components/SlideList.tsx, src/components/SlideViewer.tsx, src/components/Worklist.tsx, src/components/__tests__/Worklist.test.tsx, src/data/uids.tsx, types/dcmjs/index.d.ts, types/dicom-microscopy-viewer/index.d.ts, yarn.lock
This PR introduces changes to the application configuration and data access logic. It allows users to configure multiple servers and use each server for different types of data. Specifically, each server can be configured for one or more storage classes (by specifying the SOP Class UID for each storage class). The viewer will then construct a separate DICOMweb client for each server and use the appropriate client to search for and retrieve the corresponding data.
Currently, each SOP Class can only map to a single server. As suggested by @fedorov, it may be useful to support more than one server per SOP Class (for example to visualize image annotations from heterogeneous sources) and we can further extend the configuration logic to support these more advanced use cases as well.
=> Support configuration of multiple origin servers

craco.config.js, package.json, yarn.lock
Updates dicom-microscopy-viewer to 0.45.0 which fixes JPEG 2000 decoding errors
=> Update dicom-microscopy-viewer dependency

yarn.lock
Fix all high and critical security issues listed in the file below:
[yarn-audit.txt](https://github.com/ImagingDataCommons/slim/files/13336303/yarn-audit-final.txt)
=> fix: security issues

craco.config.js, public/config/local.js, src/App.tsx, src/services/NotificationMiddleware.js, src/utils/CustomError.js, src/utils/PubSub.js, types/dicom-microscopy-viewer/index.d.ts
Adding the ability to use a secondary annotations server passed in the url with the gcp query parameter.
Solves https://github.com/ImagingDataCommons/slim/issues/186
Before: 
Only one server allowed.
After:
https://github.com/ImagingDataCommons/slim/assets/22822446/9c01d40d-04b6-4b8c-a9e6-b00a0d9f85dc
=> feat: add secondary dicom server

src/App.tsx, src/AppConfig.d.ts, src/components/CaseViewer.tsx
#208 
```
http://localhost:3000/projects/idc-external-031/locations/us-central1/datasets/slim-bulk-ann-images/dicomStores/slim-bulk-ann-images/study/2.25.68803095896966276583382138924964839274/series/1.3.6.1.4.1.5962.99.1.1163866303.1057408148.1637546438847.2.0
```
```
http://localhost:3000/projects/idc-external-031/locations/us-central1/datasets/slim-bulk-ann-images/dicomStores/slim-bulk-ann-images/study/2.25.68803095896966276583382138924964839274/series/1.3.6.1.4.1.5962.99.1.1163866303.1057408148.1637546438847.2.0?gcp=https://healthcare.googleapis.com/v1/projects/idc-external-031/locations/us-central1/datasets/slim-bulk-ann-annotations/dicomStores/slim-bulk-ann-annotations/dicomWeb
```
=> Add GCP url support

.github/workflows/container-tests.yml, .github/workflows/deploy-to-firebase.yml, public/config/preview.js, src/components/AnnotationCategoryItem.tsx, src/components/AnnotationCategoryList.tsx, src/components/AnnotationGroupItem.tsx, src/components/AnnotationGroupList.tsx, src/components/ColorSettingsMenu.tsx, src/components/SlideViewer.tsx, src/services/NotificationMiddleware.js, src/services/RoiToAnnotationAdapter.ts, types/dicom-microscopy-viewer/index.d.ts, yarn.lock
Adding the ability to edit ROI colors based on their categories and types. Solves https://github.com/ImagingDataCommons/slim/issues/194.
=> feat - 194: ROI class based color settings

package.json, yarn.lock
Solves this issue that was generated by the last package updates:
https://github.com/ImagingDataCommons/slim/security/dependabot/73
=> chore: update rollup

src/components/SlideItem.tsx, src/components/SlideViewer.tsx
Addresses: https://github.com/ImagingDataCommons/slim/issues/225
=> feat: remove unused white space

src/components/AnnotationCategoryItem.tsx, src/components/AnnotationCategoryList.tsx, src/components/ColorSettingsMenu.tsx, src/components/HoveredRoiTooltip.tsx, src/components/SlideViewer.tsx
Addresses
https://github.com/ImagingDataCommons/slim/issues/184#issuecomment-2452617344 (i.e.: fix unexpected color change when selecting annotations)
https://github.com/ImagingDataCommons/slim/issues/184#issuecomment-2468725056 (i.e.: add ability of using only outlines or showing filled annotations)
and
https://github.com/ImagingDataCommons/slim/issues/184#issuecomment-2468730362 (i.e.: add overlay of multiple annotations on hover)
=> feat: improve annotation styles

.env, craco.config.js, src/components/SlideViewer.tsx, types/dicom-microscopy-viewer/index.d.ts, yarn.lock
- Add UI control to toggle ICC profiles
[#263](https://github.com/ImagingDataCommons/slim/issues/263)
=> feat: icc profiles toggle 

src/App.tsx, src/components/Header.tsx
=> Add new dicom store selection workflow

src/components/SlideViewer.tsx
Pre-selected SRs would show with the wrong color in the first load, as explained [here](https://github.com/ImagingDataCommons/slim/issues/184#issuecomment-2644277823). 
This PR fixes this issue, making sure the annotations have the correct color even when they are pre-selected.
Before:
Wrong colors on autoload
After:
Correct colors on autoload
=> fix: autoload annotation styles

.env, craco.config.js, package.json, yarn.lock
- Use dmv sub directory for wasm files to avoid import conflicts
- Relative for js files
- Wait for https://github.com/ImagingDataCommons/dicom-microscopy-viewer/pull/183/files
=> fix: use dmv folder for wasm files

craco.config.js, package.json, src/App.tsx, src/__mocks__/dicomMicroscopyViewerMock.js, src/components/AnnotationGroupItem.tsx, src/components/Header.tsx, src/components/SlideViewer.tsx, src/components/SlideViewer/utils/viewerUtils.ts, types/dicom-microscopy-viewer/index.d.ts, yarn.lock
- Avoid resetting annotation group visibility after selection
- Address finding selection errors
- Disable thumbnail rendering (pyramid) by default 
- Update dicom tag browser to display overview images 
Other issues:
- https://github.com/ImagingDataCommons/slim/issues/174#issuecomment-3214512913
- https://github.com/ImagingDataCommons/slim/issues/307#issuecomment-3208040059
=> fix: ui adjustments
