ImagingDataCommons/slim

.github/workflows/firebase-hosting-merge.yml, .github/workflows/firebase-hosting-pull-request.yml
- Update pull/deploy preview yamls to use new preview config.
=> Update preview config

package.json, src/components/OpticalPathItem.tsx, src/components/OpticalPathList.tsx, src/components/SlideViewer.tsx, yarn.lock
This PR fixes the update of optical path display settings when switching between slides and updates the version of the dicom-microscopy-viewer library to includes enhancements for handling overview maps.
=> Fix optical path display settings and improve handling of overview map

src/components/SlideViewer.tsx
=> Automatically select first presentation state if none is specificy via URL search parameter

.github/workflows/deploy_gh_pages.yml, package.json
Version bump to trigger DOI generation
=> Bump app version to v0.12.1

package.json, yarn.lock
The earliest fixed version is 2.0.1.
=> fix(package.json): Fix Inefficient Regular Expression Complexity in nth-check #6

.github/workflows/container-tests.yml, .github/workflows/deploy-to-firebase.yml, .github/workflows/deploy-to-github-pages.yml, .github/workflows/release.yml, .github/workflows/unit-tests.yml, .releaserc.json
- Automatically bump versions when merged back to the master
- Generate changelog
- Zip build and share it as release artifact
=> CI workflows overhaul: Add auto release and build artifact

public/config/preview.js
- Allow changing dicom store (preview)
=> feat(public/preview.js): Update preview config to allow changing dicom store

src/components/AnnotationCategoryItem.tsx, src/components/AnnotationCategoryList.tsx, src/components/SlideViewer.tsx
Adding the ability to toggle annotation groups based on their categories and types. Solves #193.
https://github.com/ImagingDataCommons/slim/assets/22822446/a5adfe8c-5804-43ac-890b-3d311b454514
=> Feat 193 class based annotation toggle

package.json, yarn.lock
=> Bump dmv version

package.json, src/components/CaseViewer.tsx, yarn.lock
- Users were not allowed to select series using gcp URLs: http://localhost:3000/projects/idc-dicom-review/locations/northamerica-northeast1/datasets/gtex/dicomStores/gtex/study/2.25.62074938789555554026716644355174628630/series/1.3.6.1.4.1.5962.99.1.2425336845.1080582547.1720412288013.4.0
=> fix(CaseViewer): Address series selection for gcp

package.json, yarn.lock
Solves semver critical vulnerabilities:
https://github.com/ImagingDataCommons/slim/security/dependabot/49
https://github.com/ImagingDataCommons/slim/security/dependabot/48
https://github.com/ImagingDataCommons/slim/security/dependabot/47
https://github.com/ImagingDataCommons/slim/security/dependabot/68
https://github.com/ImagingDataCommons/slim/security/dependabot/71
=> chore: solve critical semver and express vulnerabilities

src/components/DicomTagBrowser/DicomTagBrowser.tsx
- Searched items should display all tree
=> fix(DICOMTagBrowser): Searched items should display all tree

package.json, yarn.lock
=> feat: update dmv version

.deepsource.toml, src/components/CaseViewer.tsx, src/components/SlideViewer.tsx
-  SR: http://localhost:3000/studies/2.25.244427806814868765111946211205855976112/series/1.2.826.0.1.3680043.10.511.3.56313730225067564384463964879995066
- SEG: http://localhost:3000/studies/2.25.244427806814868765111946211205855976112/series/1.2.826.0.1.3680043.10.511.3.60381557169034098468640588489515948
- BULK ANN: http://localhost:3000/studies/2.25.106918873973188798943205935727506273925/series/1.2.826.0.1.3680043.10.511.3.62603562343778274927072899682744957
#260
=> feat: enable visualization of annotations on load

src/DicomWebManager.ts, src/components/AnnotationCategoryItem.tsx, src/components/AnnotationCategoryList.tsx, src/components/Header.tsx, src/components/SlideItem.tsx, src/components/SlideViewer.tsx, src/data/slides.tsx
- https://github.com/ImagingDataCommons/slim/issues/225#issuecomment-2679630308
=> fix: overview thumbnails

package.json, yarn.lock
=> Bump dmv version to 0.48.0

src/components/SlideItem.tsx, types/dicom-microscopy-viewer/index.d.ts
- Add a new option to disable interactions for overview viewport
=> Add disable interactions options to non volume viewports

src/components/CaseViewer.tsx, src/components/Patient.tsx, src/components/SlideItem.tsx
- #278
- https://github.com/ImagingDataCommons/slim/issues/225
=> Address series selection issue and address #278

.env, craco.config.js, package.json, yarn.lock
- Use dmv public path
- Bump dmv
- Remove homepage from package.json
=> Feat: update default config

package.json, src/App.dark.less, src/App.light.less, src/components/SlideItem.tsx, src/components/SlideViewer.tsx, src/data/slides.tsx, yarn.lock
- https://github.com/ImagingDataCommons/slim/issues/337
- https://github.com/ImagingDataCommons/slim/issues/317
- Disable seg interpolation by default
- Use thumbnail images if no overview available
=> 317: Updates
